abstract Usuario {
- nombre: String
- direccion: String
+ agregarEnvio(envio: Envio): boolean
+ {abstract} montoAPagar(from:LocalDate,to:LocalDate): Real
}
Usuario -> Envio : envios 0..*


class UsuarioPersona extends Usuario{
- dni: String
+ montoAPagar(): Real
}

class UsuarioEmpresa extends Usuario{
- cuit: String
+ montoAPagar(): Real
}

abstract Envio{
- fecha: LocalDate
- origen: String
- destino: String
- peso: Real
+{abstract} monto(): Real
+overlap(from:LocalDate,to:LocalDate): boolean 
+getPeso(): Real 
}
class EnvioLocal extends Envio{
- entregaRapida: boolean
+monto():Real
}
class EnvioInterurbano extends Envio{
-km: Integer
+ monto(): Real
}
class EnvioInternacional extends Envio{
+monto(): Real
}
