@startuml
class Usuario{
- nombre: String
- domicilio: String
+ <<create>> Usuario(nombre: String, domicilio:String)
+ getConsumos(): List<Consumo>
+ agregarConsumo(consumo: Consumo)
+ generarFactura(): Factura
}

class Consumo{
- energiaActiva: Integer
- energiaReactiva: Integer
- fecha: LocalDate
+ <<create>> Consumo(energiaActiva: Integer, energiaReactiva: Integer)
+ getFecha(): LocalDate
+ getEnergiaActiva(): Integer
+ getEnergiaReactiva(): Integer
}

class Factura{
- usuario: Usuario
- fecha: LocalDate
- bonificacion: Real
- montoFinal: Real
{static} cuadroTarifario: Real
+ <<create>> Factura(usuario:Usuario, consumo:Consumo)

}

Usuario -> Consumo : -consumos
@enduml
