@startuml

class OOBnB {
+ periodoDisponible(p:Propiedad): boolean
+ crearReserva(periodo: DateLapse, propiedad: Propiedad)
+ calcularPrecio(reserva: Reserva): Real
+ cancelarReserva(reserva: Reserva)
+ calcularIngreso(periodo: DateLapse, propietario: Usuario)
}

class Usuario{
- nombre:String
- direccion:String
- dni: integer;
+ calcularIngreso(periodo:DateLapse): Real
}

class Propiedad{
- direccion: String
- nombre: String
- precioNoche: Real
+ disponible(periodo: DateLapse): boolean
+ crearReserva(periodo: DateLapse)
+ calcularIngreso(periodo:DateLapse): Real
}

class Reserva{
- periodo: DateLapse
+ calcularPrecio(): Real
+ calcularPrecio(periodo:DateLapse): Real
}

OOBnB -> Usuario : -usuarios 0..*
Usuario -> Propiedad : -propiedades 0..*
Propiedad -> Reserva : -reservas 0..*
Reserva -> Propiedad : -propiedad 1



@enduml
