@startuml
class Usuario{
- nombre:String
- direccion:String
- dni: Integer;
+ calcularIngreso(periodo:DateLapse): Real
}

class Propiedad{
- direccion: String
- nombre: String
- precioNoche: Real
+ disponible(periodo: DateLapse): boolean
+ crearReserva(periodo: DateLapse)
+ calcularIngreso(periodo:DateLapse): Real
+ cancelar(periodo:DateLapse): Real
}

class Reserva{
- periodo: DateLapse
+ calcularPrecio(): Real
+ calcularPrecio(periodo:DateLapse): Real
+ overlap(periodo: DateLapse): boolean
+ cancelar(): boolean
- antesDeInicio(): boolean
}
interface PoliticaReserva{
+ valorReembolso(fechaInicio: LocalDate): Integer
}
class PoliticaFlexible{
+ valorReembolso(fechaInicio: LocalDate): Integer
}
class PoliticaModerada{
+ valorReembolso(fechaInicio: LocalDate): Integer
}
class PoliticaEstricta{
+ valorReembolso(fechaInicio: LocalDate): Integer
}
Usuario -> Propiedad : - propiedades 0..*
Propiedad -> Reserva : - reservas 0..*
Propiedad -> PoliticaReserva : - politica
Reserva -> Propiedad : - propiedad
PoliticaModerada ..|> PoliticaReserva
PoliticaEstricta ..|> PoliticaReserva
PoliticaFlexible ..|> PoliticaReserva
@enduml

